/**
 * Tramio Expo bare configuration.
 *
 * The native projects (ios/, android/) are not committed to source control;
 * they are regenerated by `expo prebuild` from this file plus the local
 * config plugins under `./plugins/`. Anything that would otherwise live in
 * `Info.plist` or `AndroidManifest.xml` is declared here so the manifests
 * are reproducible from source.
 *
 * Brand strings (display name, scheme, bundle identifier) are kept here for
 * task 1.1; task 1.3 will move them into `packages/branding/` and have this
 * file import from there.
 */

const IOS_BUNDLE_ID = 'app.tramio.client';
const ANDROID_PACKAGE = 'app.tramio.client';
const SCHEME = 'tramio';

const config = {
  name: 'Tramio',
  slug: 'tramio',
  version: '0.1.0',
  orientation: 'portrait',
  icon: './assets/icon.png',
  scheme: SCHEME,
  userInterfaceStyle: 'automatic',
  splash: {
    image: './assets/splash-icon.png',
    resizeMode: 'contain',
    backgroundColor: '#ffffff',
  },
  assetBundlePatterns: ['**/*'],

  ios: {
    bundleIdentifier: IOS_BUNDLE_ID,
    supportsTablet: true,
    // Background modes required to keep the tour running while the screen is
    // locked: `audio` for narration playback (Req 12.1) and `location` for
    // CoreLocation region monitoring delivery (Req 12.2, 12.3).
    // `fetch` lets the catalog/entitlement clients refresh on iOS-scheduled
    // wake-ups when on an unmetered connection (Req 3.6, 18.2, 22.5).
    infoPlist: {
      UIBackgroundModes: ['audio', 'location', 'fetch'],

      // Location permission strings (Req 11.x, 12.2). Always-on usage is
      // required so region monitoring continues to deliver geofence wakes
      // while the app is backgrounded during a tour.
      NSLocationWhenInUseUsageDescription:
        'Tramio uses your location while you ride to trigger landmark narratives along your transit route.',
      NSLocationAlwaysAndWhenInUseUsageDescription:
        'Tramio keeps narrating in the background while your phone is locked. Location is used only during an active tour.',
      NSLocationAlwaysUsageDescription:
        'Tramio keeps narrating in the background while your phone is locked. Location is used only during an active tour.',

      // Microphone is not used; speech-recognition / motion are not used in
      // the MVP. Leaving them out per Req 12.4 (declare only what we need).

      // App Transport Security: catalog/entitlement endpoints are HTTPS-only.
      NSAppTransportSecurity: {
        NSAllowsArbitraryLoads: false,
        NSExceptionDomains: {
          localhost: { NSExceptionAllowsInsecureHTTPLoads: true },
          '127.0.0.1': { NSExceptionAllowsInsecureHTTPLoads: true },
        },
      },
    },
  },

  android: {
    package: ANDROID_PACKAGE,
    predictiveBackGestureEnabled: false,
    // Cleartext only for local/dev LAN catalog. Production EAS builds ALWAYS require HTTPS —
    // the CATALOG_ALLOW_CLEARTEXT override is ignored when EAS_BUILD_PROFILE is 'production'.
    usesCleartextTraffic:
      process.env.EAS_BUILD_PROFILE !== 'production' && process.env.CATALOG_ALLOW_CLEARTEXT === '1',
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#ffffff',
    },
    // Runtime permissions for active-tour functionality (Req 12.2, 12.4).
    // ACCESS_BACKGROUND_LOCATION pairs with the foreground service to keep
    // GeofencingClient delivering DWELL events while the app is backgrounded.
    // POST_NOTIFICATIONS is required on Android 13+ so the foreground-service
    // sticky notification can be shown.
    permissions: [
      'ACCESS_FINE_LOCATION',
      'ACCESS_COARSE_LOCATION',
      'ACCESS_BACKGROUND_LOCATION',
      'FOREGROUND_SERVICE',
      'FOREGROUND_SERVICE_LOCATION',
      'FOREGROUND_SERVICE_MEDIA_PLAYBACK',
      'POST_NOTIFICATIONS',
      'WAKE_LOCK',
      'INTERNET',
      'ACCESS_NETWORK_STATE',
      // Android 16+ JobScheduler persists expo-task-manager location jobs across
      // reboot; without this, LocationTaskConsumer crashes on the first fix.
      'RECEIVE_BOOT_COMPLETED',
    ],
  },

  web: {
    favicon: './assets/favicon.png',
  },

  plugins: [
    'expo-sqlite',
    'expo-file-system',
    [
      'expo-location',
      {
        locationWhenInUsePermission:
          'Tramio uses your location while you ride to trigger landmark narratives along your transit route.',
        locationAlwaysAndWhenInUsePermission:
          'Tramio keeps narrating in the background while your phone is locked. Location is used only during an active tour.',
        locationAlwaysPermission:
          'Tramio keeps narrating in the background while your phone is locked. Location is used only during an active tour.',
        isAndroidBackgroundLocationEnabled: true,
        isAndroidForegroundServiceEnabled: true,
      },
    ],
    '@maplibre/maplibre-react-native',
    // Background location dwell delivery while the tour runs pocketed.
    'expo-task-manager',
    // Pin Android compile/target SDKs (API 37 = Android 17) and iOS deployment target for Expo SDK 57.
    [
      'expo-build-properties',
      {
        android: {
          compileSdkVersion: 37,
          targetSdkVersion: 37,
          minSdkVersion: 26,
        },
        ios: {
          deploymentTarget: '16.4',
        },
      },
    ],
    // Local plugin: declares the Android foreground service component used by
    // Location_Service + Audio_Service to keep the tour alive in the
    // background (Req 12.1, 12.2).
    './plugins/withTramioForegroundService',
    './plugins/withAndroidLocalProperties',
    // Xcode 27 / iOS 27 SDK requires UIScene lifecycle (TN3187). Remove when Expo ships it.
    './plugins/withIosSceneLifecycle',
  ],

  experiments: {
    typedRoutes: false,
  },

  extra: {
    // Backend base URLs — override in dev with your machine IP (e.g. http://192.168.1.10:8080).
    catalogBaseUrl: process.env.CATALOG_BASE_URL ?? 'http://127.0.0.1:8080',
    eas: {
      projectId: 'TBD-eas-project-id',
    },
  },
};

export default config;
