import type { ExpoConfig } from 'expo/config';

/**
 * Tramio Expo bare configuration.
 *
 * The native projects (ios/, android/) are not committed to source control;
 * they are regenerated by `expo prebuild` from this file plus the local
 * config plugins under `./plugins/`. Anything that would otherwise live in
 * `Info.plist` or `AndroidManifest.xml` is declared here so the manifests
 * are reproducible from source.
 *
 * Brand strings (display name, scheme, bundle identifier) are kept here for
 * task 1.1; task 1.3 will move them into `packages/branding/` and have this
 * file import from there.
 */

const IOS_BUNDLE_ID = 'app.tramio.client';
const ANDROID_PACKAGE = 'app.tramio.client';
const SCHEME = 'tramio';

const config: ExpoConfig = {
  name: 'Tramio',
  slug: 'tramio',
  version: '0.1.0',
  orientation: 'portrait',
  icon: './assets/icon.png',
  scheme: SCHEME,
  userInterfaceStyle: 'automatic',
  newArchEnabled: true,
  splash: {
    image: './assets/splash-icon.png',
    resizeMode: 'contain',
    backgroundColor: '#ffffff',
  },
  assetBundlePatterns: ['**/*'],

  ios: {
    bundleIdentifier: IOS_BUNDLE_ID,
    supportsTablet: true,
    // Background modes required to keep the tour running while the screen is
    // locked: `audio` for narration playback (Req 12.1) and `location` for
    // CoreLocation region monitoring delivery (Req 12.2, 12.3).
    // `fetch` lets the catalog/entitlement clients refresh on iOS-scheduled
    // wake-ups when on an unmetered connection (Req 3.6, 18.2, 22.5).
    infoPlist: {
      UIBackgroundModes: ['audio', 'location', 'fetch'],

      // Location permission strings (Req 11.x, 12.2). Always-on usage is
      // required so region monitoring continues to deliver geofence wakes
      // while the app is backgrounded during a tour.
      NSLocationWhenInUseUsageDescription:
        'Tramio uses your location while you ride to trigger landmark narratives along your transit route.',
      NSLocationAlwaysAndWhenInUseUsageDescription:
        'Tramio keeps narrating in the background while your phone is locked. Location is used only during an active tour.',
      NSLocationAlwaysUsageDescription:
        'Tramio keeps narrating in the background while your phone is locked. Location is used only during an active tour.',

      // Microphone is not used; speech-recognition / motion are not used in
      // the MVP. Leaving them out per Req 12.4 (declare only what we need).

      // App Transport Security: catalog/entitlement endpoints are HTTPS-only.
      NSAppTransportSecurity: {
        NSAllowsArbitraryLoads: false,
      },
    },
  },

  android: {
    package: ANDROID_PACKAGE,
    edgeToEdgeEnabled: true,
    predictiveBackGestureEnabled: false,
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      backgroundColor: '#ffffff',
    },
    // Runtime permissions for active-tour functionality (Req 12.2, 12.4).
    // ACCESS_BACKGROUND_LOCATION pairs with the foreground service to keep
    // GeofencingClient delivering DWELL events while the app is backgrounded.
    // POST_NOTIFICATIONS is required on Android 13+ so the foreground-service
    // sticky notification can be shown.
    permissions: [
      'ACCESS_FINE_LOCATION',
      'ACCESS_COARSE_LOCATION',
      'ACCESS_BACKGROUND_LOCATION',
      'FOREGROUND_SERVICE',
      'FOREGROUND_SERVICE_LOCATION',
      'FOREGROUND_SERVICE_MEDIA_PLAYBACK',
      'POST_NOTIFICATIONS',
      'WAKE_LOCK',
      'INTERNET',
      'ACCESS_NETWORK_STATE',
    ],
  },

  web: {
    favicon: './assets/favicon.png',
  },

  plugins: [
    // Pin Android compile/target SDKs and iOS deployment target to versions
    // that support the foreground-service / region-monitoring APIs the
    // Location_Service turbo module relies on.
    [
      'expo-build-properties',
      {
        android: {
          compileSdkVersion: 35,
          targetSdkVersion: 35,
          minSdkVersion: 26,
        },
        ios: {
          deploymentTarget: '15.1',
        },
      },
    ],
    // Local plugin: declares the Android foreground service component used by
    // Location_Service + Audio_Service to keep the tour alive in the
    // background (Req 12.1, 12.2).
    './plugins/withTramioForegroundService',
  ],

  experiments: {
    typedRoutes: false,
  },

  extra: {
    // Backend base URLs are resolved at runtime from environment-based config
    // (`.env.{profile}`) rather than hard-coded here. See design.md
    // "Branding module > Runtime configuration".
    eas: {
      projectId: 'TBD-eas-project-id',
    },
  },
};

export default config;
