// @ts-check
const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const os = require('os');
const path = require('path');

/**
 * Writes `android/local.properties` with `sdk.dir` during prebuild.
 * `expo prebuild --clean` wipes `android/`; without this file Gradle
 * cannot find the Android SDK on a fresh checkout.
 *
 * @type {import('@expo/config-plugins').ConfigPlugin}
 */
const withAndroidLocalProperties = (config) => {
  return withDangerousMod(config, [
    'android',
    async (modConfig) => {
      const sdkDir =
        process.env.ANDROID_HOME ??
        process.env.ANDROID_SDK_ROOT ??
        path.join(os.homedir(), 'Library', 'Android', 'sdk');

      const propsPath = path.join(modConfig.modRequest.platformProjectRoot, 'local.properties');
      const escaped = sdkDir.replace(/\\/g, '\\\\');
      fs.writeFileSync(
        propsPath,
        `# Auto-generated by withAndroidLocalProperties during expo prebuild\nsdk.dir=${escaped}\n`,
      );
      return modConfig;
    },
  ]);
};

module.exports = withAndroidLocalProperties;
